server:
  port: 6211
spring:
  application:
    name: base-user
  datasource:
    url: jdbc:mysql://192.168.236.8/insight_base?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: set names utf8mb4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    tomcat:
      initial-size: 100
      min-idle: 100
      max-idle: 1000
      max-wait: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.236.8
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    addresses: 192.168.236.8:5672
    username: root
    password: root
    publisher-confirms: false
    publisher-returns: false
    template:
      mandatory: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.236.8:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
ribbon:
  ServerListRefreshInterval: 3000
  ReadTimeout: 10000
  ConnectTimeout: 5000
logging:
  level:
    com.insight: debug
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss.SSS} gateway [%-5level] %X{requestId} %logger{35} : %msg%n
mybatis:
  configuration:
    map-underscore-to-camel-case: true
